services:
  # SERVEUR POSTGRES
  bdd:
    image: "postgres:16-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "backend"
      POSTGRES_PASSWORD: "backend"
      POSTGRES_USER: "backend"

  # INTERFACE ADMINER POUR LE PROJET POSTGRESQL
  adminer:
    image: adminer
    ports:
      - 8081:8080 
    environment:
      ADMINER_DEFAULT_SERVER: bdd
    depends_on:
      - bdd

  # SERVEUR NODEJS
  node:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    environment:
      - PG_URL=postgres://backend:backend@bdd:5432/backend
    command: sleep inf
    depends_on:
      - bdd

  
